doctrine:
    dbal: { connections: { default: { host: [[softdbhost]], port: 3306, user: [[softdbuser]], password: "[[softdbpass]]", dbname: [[softdb]], mapping_types: { enum: string, bit: boolean }, server_version: [[dbser_ver]] } } }
