# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: [[reg_date]]
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

[[admin_username]]:[[admin_pass]]:[[admin_realname]]:[[admin_email]]:admin,user
