<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		[[generator]]
 * Date [[date_at]]
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLDSCGenDate is an internal mark
   $CLDSCGenDate = "[[timestamp]]";

/* cldsc_use_new_ordering_of_labels : Display description elements corresponding to others at the end */
$GLOBALS['cldsc_use_new_ordering_of_labels'] = FALSE;



?>