parameters:
    database.driver:        mysql
    database.host:          [[softdbhost]]
    database.port:          3306
    database.name:          [[softdb]]
    database.user:          [[softdbuser]]
    database.password:      [[softdbpass]]

    kernel.secret:          [[kernel_secret]]

    fork.debug_email:       [[admin_email]]
    fork.debug_message:     'Internal error.'
    fork.version:           '5.11.1'

    session.cookie_secure:  false
    site.protocol:          http
    site.domain:            [[domhost]]
    site.default_title:     Fork CMS
    site.multilanguage:     false
    site.default_language:  en
    site.path_www:          "%kernel.project_dir%"

    action.group_tag:       '\@actiongroup'
    action.rights_level:    7
