<?php

/**
 * -----------------------------------------------------------------------------
 * Generated [[Generated_time]]
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '9.1.3',
    'version_db_installed' => '20220908074900',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => [[timestamp]],
    ],
];
