<?php
/* Auto generated by installer on [[regtime]] */
define('SCHLIX_SITE_NAME','[[site_name]]');
define('SCHLIX_SITE_HTTP_URL','[[protocol]]://'.$_SERVER['HTTP_HOST'] ); /* Automatic URL */ 
define('SCHLIX_SITE_HTTPS_URL',[[SCHLIX_SITE_HTTPS_URL]]); /* if you have  a valid SSL certificate,  change this to 'https://'.$_SERVER['HTTP_HOST'] and set SCHLIX_SITE_SSL_ENABLED to true */ 
define('SCHLIX_SITE_PATH',str_replace('\\','/',dirname(__FILE__)));
define('SCHLIX_DEFAULT_USER_CLASS','users'); /* Default user class - e.g: LDAP, smf forum, opencart, etc */
define('SCHLIX_DEFAULT_LANGUAGE','[[language]]'); /* Default Language */ 
define('SCHLIX_DEFAULT_ADMIN_GROUP','Administrators');
define('SCHLIX_SITE_OFFLINE',false); /* Set this to yes if you want to make your site offline for visitors */ 
define('SCHLIX_SEF_ENABLED', true);
define('SCHLIX_SITE_SSL_ENABLED',[[SCHLIX_SITE_SSL_ENABLED]]); /* indicate whether you have an SSL cerificate for your website */ 
define('SCHLIX_FORCE_SSL_ADMIN_LOGIN',[[SCHLIX_FORCE_SSL_ADMIN_LOGIN]]); /* force admin to login via SSL */
define('SCHLIX_DB_HOST','[[softdbhost]]'); /* database host, e.g. localhost */
define('SCHLIX_DB_DATABASE','[[softdb]]'); /* database name */
define('SCHLIX_DB_USERNAME','[[softdbuser]]'); /* database username */
define('SCHLIX_DB_PASSWORD','[[softdbpass]]'); /* database password */
///////// advanced db param - leave blank for default /////////
define('SCHLIX_DB_PORT',0); /* if the value is zero then it will use the default port number, usually 3306 for mysql */ 
define('SCHLIX_DB_SOCKET',''); /* if the value is blank then it will the default value */
define('SCHLIX_DB_USE_SSL',0); /* set this to true if MySQL uses SSL connection */
define('SCHLIX_DB_SSL_CA',''); /* specify the SSL CA certificate file if SCHLIX_DB_USE_SSL is set to true */
///////// end advanced db param  /////////define('SCHLIX_PAGE_CACHE_ENABLED', false);
define('SCHLIX_SQL_ENFORCE_ROW_LIMIT', true);
define('SCHLIX_SQL_CACHE_ENABLED', false);
define('SCHLIX_SQL_CACHE_TIME', 0);
define('SCHLIX_SESSION_LOGIN_TIME',7200); /* in seconds - this should be short, e.g. 30 minutes to 3 hours */ 
define('SCHLIX_SESSION_REMEMBER_COOKIE_TIME', 172800); /* in seconds - this should be longer than the login time */ 
define('SCHLIX_COOKIE_SAMESITE', 'none'); /* Samesite=none cookie for HTTPS by default as per new standard in 2020 */ 
define('SCHLIX_ADMIN_THEME','admindefault');
define('SCHLIX_USER_IMAGE_DIRECTORY',SCHLIX_SITE_PATH.'/media/images');
define('SCHLIX_MAIL_DEFAULT_SENDER','[[admin_username]]'); /* Default sender name, e.g. Webmaster */
define('SCHLIX_MAIL_DEFAULT_EMAIL','[[admin_email]]'); /* Default email address for sending out an email if none specified */
define('SCHLIX_SMTP_HOST', ''); /* If you use an external SMTP server, fill in the server host here */
define('SCHLIX_SMTP_PORT', 25); /* Some common values: 25, 587 (TLS), 465 (SSL) */
define('SCHLIX_SMTP_USE_AUTH', false); /* Specify whether an SMTP authentication is required */
define('SCHLIX_SMTP_USERNAME', ''); /* Fill in the SMTP username if SMTP authentication is required */ 
define('SCHLIX_SMTP_PASSWORD', ''); /* Fill in the password for the SMTP user if SMTP authentication is required */
define('SCHLIX_SMTP_SECURITY', ''); /* possible values: tls (port 587), ssl (port 465) or simply blank (port 25) */
define('SCHLIX_SMTP_SECURITY_SELF_SIGNED', 0); /* true/false value - allow self signed certificate */
 /* Oauth2 */
define('SCHLIX_SMTP_OAUTH2_PROVIDER', ''); /* OAUTH2 providers - google, microsoft, yahoo */ 
define('SCHLIX_SMTP_OAUTH2_CLIENT_ID', ''); /* OAUTH2 Client/Application ID */ 
define('SCHLIX_SMTP_OAUTH2_SECRET', ''); /* OAUTH2 secret */ 
define('SCHLIX_SMTP_OAUTH2_REFRESH_TOKEN', ''); /* OAUTH2 offline refresh token */ 
define('SCHLIX_SYSTEM_TIMEZONE', 'America/New_York'); /* default website timezone */
define('SCHLIX_JS_MODE',3); /* Javascript mode. 1 = Debug, 2 = Minified, 3 = Minified and Gzipped */ 
define('SCHLIX_RECORD_404_ERRORS','0'); /* Record 404 errors in the database */ 
/**********************************************************************/
/* Do not modify the SCHLIX_SITE_URL - this is for auto http/https switch */
define('SCHLIX_SITE_URL', (defined('SCHLIX_SITE_HTTPS_URL') && SCHLIX_SITE_SSL_ENABLED && SCHLIX_SITE_HTTPS_URL !='' && ($_SERVER['HTTPS']==='on' || $_SERVER['HTTPS']===1 || $_SERVER['SERVER_PORT']===443)) ? SCHLIX_SITE_HTTPS_URL : SCHLIX_SITE_HTTP_URL);
/**********************************************************************/
error_reporting(E_ERROR|E_PARSE|E_CORE_ERROR|E_CORE_WARNING|E_COMPILE_ERROR|E_COMPILE_WARNING|E_USER_ERROR|E_RECOVERABLE_ERROR|E_WARNING);
@ini_set('display_errors',1);
